const names = require('./module-1')
const sayHi = require('./module2')
const newflav = require('./newflavour')
console.log(newflav)
console.log(names)
require('./mind-grenade')
//  sayHi('lucy')
//  sayHi(names.john)
//  sayHi(names.peter)
